title: "Blog của Robo"
description: "Nơi chia sẻ những điều thú vị"
baseurl: "/Blog_Cua_Toi"
url: "https://roboeinlife-glitch.github.io"

theme: jekyll-theme-cayman
show_downloads: true

# QUAN TRỌNG: Đổi permalink
permalink: /:year/:month/:day/:title:output_ext

# Thêm cài đặt markdown
markdown: kramdown
highlighter: rouge
timezone: Asia/Ho_Chi_Minh
future: true
