title: "Blog của Robo"
description: "Nơi chia sẻ những điều thú vị"
baseurl: "/Blog_Cua_Toi"
url: "https://roboeinlife-glitch.github.io"

show_downloads: true

# QUAN TRỌNG: Đổi permalink
permalink: /:year/:month/:day/:title:output_ext

# Thêm cài đặt markdown
markdown: kramdown
highlighter: rouge
timezone: Asia/Ho_Chi_Minh
future: true

plugins:
  - jekyll-remote-theme  

social:
  name: RoboE_inlife 
  links:
    - https://github.com/roboeinlife-glitch
    - https://x.com/roboe_inlife
    - https://www.youtube.com/@RoboE_Life
   
